source 'https://rubygems.org' 
gem 'nokogiri'
gem 'trollop'
gem 'ruby-progressbar'
gem 'rubyzip'
gem 'zip-zip'
gem 'pry',  '~>0.10.0'
gem 'ruby-oci8'
gem 'axlsx'
gem 'colorize'
gem 'sqlite3'
gem 'activerecord'
gem 'activerecord-import'
gem 'awesome_print'
gem 'rspec'
